/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amoya' at '23/08/15 06:34 PM' with Gradle 2.5-rc-2
 *
 * @author amoya, @date 23/08/15 06:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
